name = "Newb X Lowres Renewed"
version = [0, 1, 2]
min_supported_mc_version = [1, 21, 20]
description = '''
To have §bNewb §fX §aLowres §fyou need to have the apk patch §a+1.21.20
§fShader By §9MisaLowZz
''' # %w = patch warning, %v = version
authors = ["MisaLowzZ", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "323bf99d-aab0-432a-8ec4-fd5329551f58" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "EndSky", "Clouds", "SunMoon", "RenderChunk", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "MULTILAYER_CLOUDS"
materials = ["Clouds"]
description = '''
Multilayer Clouds

This subpack adds two cloud layers
§c[Not recommended on low-end devices]§f
'''

[[subpack]]
define = "CHUNK_ANIM"
materials = ["RenderChunk"]
description = '''
Chunk Loading Animation

This subpack enables the chunk loading animation
§a[Recommended on low-end devices]§f
'''

[[subpack]]
define = "GROUND_REFLECTION"
materials = ["RenderChunk"]
description = '''
Ground Reflection

This subpack enables reflection on the ground
§b[Does not affect performance]§f
'''

[[subpack]]
define = "INTENSE_FOG"
materials = ["RenderChunk"]
description = '''
Intense Fog

This subpack enables strong and dense fog
§6[Can cause fps drop]§f
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No Wave Effects

This subpack disables plant and water movements
§a[Recommended on low-end devices]§f
'''

[[subpack]]
define = "NO_AURORAS"
materials = ["Clouds"]
description = '''
No Auroras

This subpack disables the auroras that are seen at night
§b[Does not affect performance]§f
'''

[[subpack]]
define = "SIMPLE_WATER"
materials = ["RenderChunk"]
description = '''
Simple Water

This subpack enables a simple, flat water design
§a[Recommended on low-end devices]§f
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default

Subpack default 
'''
